emotion ThemeProvider 추가 & eslint 설정 변경
okbut/corporate-library-front pull request #18
Opened 2021-12-08 18:36 UTC by thehue

emotion theme을 적용하면서 폴더구조가 변경되었습니다.
test파일, 절대 경로 못 읽는 것, import/extensions eslint error때문에 설정을 변경하였습니다

* 폴더 구조 참고 링크 : https://dev.to/vadorequest/a-2021-guide-about-structuring-your-next-js-project-in-a-flexible-and-efficient-way-472

색 팔레트는 저희 사용할 템플릿 이용해서 컬러차트 뽑아서 만들었습니다.
추후에 더 필요한 색상은 추가하면 될 것 같아요 :)

http://mcg.mbitson.com/#!?mcgpalette0=%2300ab55&mcgpalette1=%23ff4842&mcgpalette2=%23212b36&themename=green

<img width="1304" alt="스크린샷 2021-12-09 오전 3 33 45" src="https://user-images.githubusercontent.com/45552388/145264590-6cf00f67-6123-4354-be8d-5a0ddbc86e80.png">

2021-12-10 13:56 UTC, onethegarden requested changes
디스코드에서 이야기 나누었던 것 토대로 리뷰 작성하였습니다 
확인 부탁드립니다 :)

2021-12-10 13:56 UTC, onethegarden commented on src/styles/emotion.d.ts
> +type Key = 50 | 100 | 200 | 300 | 400 | 500 | 600 | 700 | 800 | 900 | 'A100' | 'A200' | 'A400' | 'A700';
저번에 메세지로 이야기 나누었던 것과 같이 사용하지 않는 타입이라 삭제하시면 될 것 같습니다 :)

2021-12-10 13:56 UTC, onethegarden commented on .eslintrc.json
> +}
마지막 라인에 공백이 누락되어 있네요 이 부분은 POSIX 명세를 찾아보시면 확인할 수 있습니다  :)

2021-12-10 13:56 UTC, onethegarden commented on src/styles/theme.ts
> +  smallest: '25em', // 400px
이 부분도 메세지로 말씀하신 것과 같이 rem으로 수정부탁드립니다 :)

2021-12-19 08:17 UTC, thehue commented on .eslintrc.json
> +}
POSIX 처음 알았네요!

2021-12-19 08:19 UTC, thehue commented
피드백 반영해서 push해 두었습니다!

2021-12-19 08:23 UTC, thehue commented on package.json
> +    "lint": "eslint --ext ts,tsx .",
eslint가 에러 못 잡길래 위처럼 수정하였는데, js, jsx도 포함되게 해야될까요?

2021-12-28 06:30 UTC, onethegarden commented on package.json
> +    "lint": "eslint --ext ts,tsx .",
앗 늦게 봤ㄴㅔ요.... 테스트 코드는 ts만 작성할 것 같아서 괜찮을 것 같습니다!

2021-12-28 06:31 UTC, onethegarden approved these changes

2021-12-30 06:37 UTC, merged