Add recoil react query
okbut/corporate-library-front pull request #9
Opened 2021-11-20 15:32 UTC by hyunmyungJaneLee

recoil과 react-query 세팅을 적용했습니다.

react-query는 동작 테스트할 수 있도록 샘플 파일들도 생성했습니다.
이 부분은 추후에 삭제하도록 하겠습니다!

2021-11-20 23:34 UTC, onethegarden requested changes
구체적인 예시 페이지들 까지 적용해 주셔서 
나중에 참고하면서 적용하기 편리할 것 같습니다 👍

다만 추가하신 파일들이 eslint 에러가 나는 부분이 있네요,,
 이 부분만 확인 하시면 좋을 것 같습니다 😊

2021-11-20 23:34 UTC, onethegarden commented on package.json
> +    "eslint-plugin-react-hooks": "^4.3.0",
이 부분은 `devDependencies` 에 설정해 두었기 때문에
 추가할 필요 없을 것 같습니다 😊

2021-11-20 23:34 UTC, onethegarden commented on pages/person/index.tsx
> +    });
예시까지 구체적으로 적용해 두셨네요! 참고하여 사용하기 편리할 것 같습니다. 👍

2021-11-21 06:11 UTC, hyunmyungJaneLee commented
lint 에러 나는 부분 수정해서 반영했습니다!!

2021-11-21 10:59 UTC, onethegarden submitted a review, later dismissed

2021-11-22 13:16 UTC, merged